### ISSUE TITLE
AttributeError: partially initialized module 'sabnzbd' has no attribute 'nzbstuff' (most likely due to a circular import)

### ISSUE THREAD

**Issue by sanderjo** [mnightingale/sabnzbd#8]
### SABnzbd version

mnightingale

### Operating system

docker

### Using Docker image

Other

### Description

Building the docker goes well, but running:

```
NUC12DCMi7:~/git/sabnzbd-with-pipelining$ sudo docker run sanderjo/sabnzbd-pipelining
Traceback (most recent call last):
  File "/sabnzbd/SABnzbd.py", line 65, in <module>
    import sabnzbd
  File "/sabnzbd/sabnzbd/__init__.py", line 85, in <module>
    import sabnzbd.rss as rss
  File "/sabnzbd/sabnzbd/rss.py", line 44, in <module>
    import sabnzbd.emailer as emailer
  File "/sabnzbd/sabnzbd/emailer.py", line 36, in <module>
    from sabnzbd.notifier import check_cat
  File "/sabnzbd/sabnzbd/notifier.py", line 41, in <module>
    from sabnzbd.newsunpack import create_env
  File "/sabnzbd/sabnzbd/newsunpack.py", line 68, in <module>
    from sabnzbd.nzbstuff import NzbObject
  File "/sabnzbd/sabnzbd/nzbstuff.py", line 98, in <module>
    from sabnzbd.downloader import Server
  File "/sabnzbd/sabnzbd/downloader.py", line 37, in <module>
    from sabnzbd.newswrapper import NewsWrapper, NNTPPermanentError
  File "/sabnzbd/sabnzbd/newswrapper.py", line 54, in <module>
    class NewsWrapper:
  File "/sabnzbd/sabnzbd/newswrapper.py", line 121, in NewsWrapper
    def article(self) -> Optional[sabnzbd.nzbstuff.Article]:
                                  ^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'sabnzbd' has no attribute 'nzbstuff' (most likely due to a circular import)
NUC12DCMi7:
```

**Comment by sanderjo** [comment]
Caused by https://github.com/sabnzbd/sabnzbd/commit/e8d1b7ab3c710c43c465c09c0081df5e5d546bed ?

**Comment by mnightingale** [comment]
If I follow correctly, I believe it's because nzbstuff has an `import sabnzbd` and so does newswrapper.

I'd done it elsewhere already, but @Safihre am I ok to use `Optional["sabnzbd.nzbstuff.Article"]` because I don't think I can fix the circular imports and I'd rather have typing. [PEP-0484](https://peps.python.org/pep-0484/#forward-references) I think it's only needed like that on function signatures.

**Comment by mnightingale** [comment]
It's fixed, I think `Optional["sabnzbd.nzbstuff.Article"]` is as good as we can do.
